# /etc/NetworkManager/conf.d/10-wifi-ap.conf
# Запрещает NetworkManager управлять WiFi AP интерфейсом (wlan0)
# и связанными виртуальными интерфейсами
# Устанавливается автоматически install.sh

[keyfile]
unmanaged-devices=interface-name:wlan0;interface-name:wlan0_5g
