#!/bin/bash
# =============================================================================
# setup-dns.sh — DNS mode configurator for dnsmasq
#
# Config vars in /etc/ltemod/ltemod.conf:
#   DNS_MODE="system|custom|dot"
#     system — remove ltemod DNS overrides, use dnsmasq defaults
#     custom — write specific upstream servers to dnsmasq config
#     dot    — install stubby (DoT), forward dnsmasq to 127.0.0.1#53153
#   DNS_SERVER="1.1.1.1"   (comma-separated, e.g. "1.1.1.1,8.8.8.8")
#
# Output config: /etc/dnsmasq.d/ltemod-dns.conf
#
# Usage:
#   setup-dns.sh apply   — apply DNS_MODE from config
#   setup-dns.sh status  — show current mode and upstream servers
#   setup-dns.sh test    — test DNS resolution
# =============================================================================

set -uo pipefail

CONFIG_FILE="${CONFIG_FILE:-/etc/ltemod/ltemod.conf}"
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE"

DNS_MODE="${DNS_MODE:-system}"
DNS_SERVER="${DNS_SERVER:-1.1.1.1}"

DNSMASQ_CONF="/etc/dnsmasq.d/ltemod-dns.conf"
STUBBY_CONF="/etc/stubby/stubby.yml"
STUBBY_PORT=53153

log() {
    logger -t ltemod-dns "$*"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

log_err() {
    logger -t ltemod-dns -p user.err "$*"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2
}

reload_dnsmasq() {
    if systemctl is-active --quiet dnsmasq 2>/dev/null; then
        systemctl reload-or-restart dnsmasq && log "dnsmasq reloaded" || \
            log_err "Failed to reload dnsmasq (continuing)"
    else
        log "dnsmasq is not running — skipping reload"
    fi
}

# ---------------------------------------------------------------------------
# Build stubby upstream block for a single server IP.
# Returns YAML fragment.
# ---------------------------------------------------------------------------
stubby_upstream_for_ip() {
    local srv="$1"
    case "$srv" in
        1.1.1.1)
            cat <<EOF
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
    tls_port: 853
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
    tls_port: 853
EOF
            ;;
        9.9.9.9)
            cat <<EOF
  - address_data: 9.9.9.9
    tls_auth_name: "dns.quad9.net"
    tls_port: 853
  - address_data: 149.112.112.112
    tls_auth_name: "dns.quad9.net"
    tls_port: 853
EOF
            ;;
        8.8.8.8)
            cat <<EOF
  - address_data: 8.8.8.8
    tls_auth_name: "dns.google"
    tls_port: 853
  - address_data: 8.8.4.4
    tls_auth_name: "dns.google"
    tls_port: 853
EOF
            ;;
        *)
            # Unknown server: use it as-is (no TLS auth name known)
            log "Warning: no known TLS name for $srv — using without tls_auth_name"
            cat <<EOF
  - address_data: ${srv}
    tls_port: 853
EOF
            ;;
    esac
}

# ---------------------------------------------------------------------------
# Build complete stubby.yml from DNS_SERVER (comma-separated).
# Falls back to Cloudflare + Quad9 if DNS_SERVER is empty or unrecognised.
# ---------------------------------------------------------------------------
write_stubby_conf() {
    mkdir -p "$(dirname "$STUBBY_CONF")"

    # Build upstream list
    local upstreams=""
    local servers_seen=0

    # Split comma-separated list
    local IFS_ORIG="$IFS"
    IFS=',' read -ra srv_list <<< "$DNS_SERVER"
    IFS="$IFS_ORIG"

    for srv in "${srv_list[@]}"; do
        srv="${srv// /}"   # trim spaces
        [[ -z "$srv" ]] && continue
        upstreams+="$(stubby_upstream_for_ip "$srv")"$'\n'
        servers_seen=$((servers_seen + 1))
    done

    # Default: Cloudflare + Quad9
    if [[ $servers_seen -eq 0 ]]; then
        log "DNS_SERVER empty — defaulting to Cloudflare + Quad9 for DoT"
        upstreams+="$(stubby_upstream_for_ip 1.1.1.1)"$'\n'
        upstreams+="$(stubby_upstream_for_ip 9.9.9.9)"$'\n'
    fi

    cat > "$STUBBY_CONF" <<EOF
# Generated by ltemod setup-dns.sh — do not edit manually
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private: 1
round_robin_upstreams: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1@${STUBBY_PORT}
upstream_recursive_servers:
${upstreams}
EOF
    log "Written $STUBBY_CONF"
}

# ---------------------------------------------------------------------------
# Mode: custom
# Write explicit server= lines to dnsmasq config.
# ---------------------------------------------------------------------------
mode_custom() {
    log "Applying DNS mode: custom (servers: $DNS_SERVER)"

    local conf_content="# Generated by ltemod setup-dns.sh\nno-resolv\n"

    local IFS_ORIG="$IFS"
    IFS=',' read -ra srv_list <<< "$DNS_SERVER"
    IFS="$IFS_ORIG"

    for srv in "${srv_list[@]}"; do
        srv="${srv// /}"
        [[ -z "$srv" ]] && continue
        conf_content+="server=${srv}\n"
    done

    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    printf "%b" "$conf_content" > "$DNSMASQ_CONF"
    log "Written $DNSMASQ_CONF"

    reload_dnsmasq
}

# ---------------------------------------------------------------------------
# Mode: dot (DNS-over-TLS via stubby)
# ---------------------------------------------------------------------------
mode_dot() {
    log "Applying DNS mode: dot"

    # 1. Install stubby if missing
    if ! command -v stubby &>/dev/null; then
        log "stubby not found — installing..."
        if ! apt-get install -y stubby -qq 2>/dev/null; then
            log_err "apt-get install stubby failed — aborting DoT setup"
            return 1
        fi
        log "stubby installed"
    fi

    # 2. Write stubby config
    write_stubby_conf

    # 3. Start/restart stubby
    systemctl restart stubby 2>/dev/null || {
        log_err "Failed to restart stubby — aborting DoT setup"
        return 1
    }
    log "stubby restarted, listening on 127.0.0.1:${STUBBY_PORT}"

    # 4. Write dnsmasq config to forward to stubby
    mkdir -p "$(dirname "$DNSMASQ_CONF")"
    cat > "$DNSMASQ_CONF" <<EOF
# Generated by ltemod setup-dns.sh
no-resolv
server=127.0.0.1#${STUBBY_PORT}
EOF
    log "Written $DNSMASQ_CONF (forwarding to stubby)"

    reload_dnsmasq
}

# ---------------------------------------------------------------------------
# Mode: system
# Remove ltemod DNS overrides, stop stubby.
# ---------------------------------------------------------------------------
mode_system() {
    log "Applying DNS mode: system (removing overrides)"

    if [[ -f "$DNSMASQ_CONF" ]]; then
        rm -f "$DNSMASQ_CONF"
        log "Removed $DNSMASQ_CONF"
    else
        log "$DNSMASQ_CONF not present — nothing to remove"
    fi

    # Stop stubby if it's running
    if systemctl is-active --quiet stubby 2>/dev/null; then
        systemctl stop stubby 2>/dev/null && log "Stopped stubby" || \
            log_err "Could not stop stubby (continuing)"
    fi

    reload_dnsmasq
}

# ---------------------------------------------------------------------------
# Command: status
# ---------------------------------------------------------------------------
cmd_status() {
    echo "=== DNS Status ==="
    echo "  DNS_MODE:    ${DNS_MODE}"
    echo "  DNS_SERVER:  ${DNS_SERVER}"
    echo ""

    if [[ -f "$DNSMASQ_CONF" ]]; then
        echo "  Active config ($DNSMASQ_CONF):"
        while IFS= read -r line; do
            echo "    $line"
        done < "$DNSMASQ_CONF"
    else
        echo "  No ltemod dnsmasq config (system defaults in use)"
    fi
    echo ""

    echo "  dnsmasq:  $(systemctl is-active dnsmasq 2>/dev/null || echo 'unknown')"
    echo "  stubby:   $(systemctl is-active stubby  2>/dev/null || echo 'not installed or unknown')"
}

# ---------------------------------------------------------------------------
# Command: test
# ---------------------------------------------------------------------------
cmd_test() {
    local test_domain="google.com"
    echo "=== DNS Resolution Test (${test_domain}) ==="

    if command -v dig &>/dev/null; then
        dig +short "$test_domain" A
    elif command -v nslookup &>/dev/null; then
        nslookup "$test_domain" 2>&1 | grep -E "Address|Name"
    elif command -v host &>/dev/null; then
        host "$test_domain"
    else
        log_err "No DNS test tool found (dig / nslookup / host)"
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Command: apply
# ---------------------------------------------------------------------------
cmd_apply() {
    log "=== Applying DNS configuration: mode=$DNS_MODE ==="
    case "$DNS_MODE" in
        custom) mode_custom ;;
        dot)    mode_dot    ;;
        system) mode_system ;;
        *)
            log_err "Unknown DNS_MODE: '$DNS_MODE' — must be system, custom, or dot"
            exit 1
            ;;
    esac
    log "=== DNS configuration applied ==="
}

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 && "${1:-}" != "status" && "${1:-}" != "test" ]]; then
    log_err "Must be run as root"
    exit 1
fi

case "${1:-}" in
    apply)  cmd_apply  ;;
    status) cmd_status ;;
    test)   cmd_test   ;;
    *)
        echo "Usage: $0 {apply|status|test}"
        exit 1
        ;;
esac
